server:
  port: 5001

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:h2:mem:airline_location
    username: we
    password: we
    driver-class-name: org.h2.Driver
    h2:
      console:
        enabled: true
        path: /h2-console
    jpa:
      hibernate:
        ddl-auto: update

  #  datasource:
  #    url: jdbc:mysql://localhost:3306/airline_location_db
  #    username: we
  #    password: we
