server:
  port: 5001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/airline_location_db
    username: we
    password: we

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    #si registra con ip adress non con hostname
    prefer-ip-address: true